apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  replicas: {{ .Values.replica }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      volumes:
        - name: logs
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pvc
      containers:
        - name: {{ .Release.Name }}
          volumeMounts:
            - mountPath: /service_log
              name: logs
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.port }}
          env:
            - name: GIN_MODE
              value: "release"
            - name: DATABASE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-cf
                  key: database_username
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-cf
                  key: database_host
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-cf
                  key: database_port
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-cf
                  key: database_name
            - name: JWT_EXPIRE_TIME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-cf
                  key: jwt_expire_time
            - name: DATABASE_MIGRATION
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-cf
                  key: database_migration
            - name: DATABASE_INITIALIZATION_DATA
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-cf
                  key: database_initialization_data
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: database_password
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: jwt_secret_key
