apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  database_password: {{ .Values.database_password }}
  jwt_secret_key: {{ .Values.jwt_secret_key }}
