def images_name = 'tuanloc/room-mate-finance'
def app_name = 'room-mate-finance'
def app_namespace = 'finance-service'
def replica = 2

pipeline {
    agent any
    tools {
        go "1.22.2"
    }
    environment {
        GIT_CREDENTIALS_ID = 'tuanloc-github'
        APPLICATION_GIT_BRANCH = '*/dev'
        APPLICATION_GIT_REPOSITRY = 'https://github.com/tuanloc1105/room-mate-finance-go-service.git'
        SSH_USER='ae403'
        SSH_HOST='192.168.1.22'
        SSH_PORT='22'
        TARGET_DIR='/home/ae403/service/room-mate-finance'
    }
    stages {
        stage('Checkout source') {
            steps {
                script {
                    def checkoutDetails = checkout scmGit(
                        branches: [[name: APPLICATION_GIT_BRANCH]],
                        extensions: [],
                        userRemoteConfigs: [
                            [credentialsId: GIT_CREDENTIALS_ID, url: APPLICATION_GIT_REPOSITRY]
                        ]
                    )
                    sh "echo $checkoutDetails"
                }
            }
        }
        stage('Deploy source') {
            steps {
                script {
                    withCredentials([string(credentialsId: 'tuanloc-docker-credential', variable: 'DOCKER_HUB_PASSWORD')]) { // create a credential as a secret text in jenkins credential page
                        sh "ssh $SSH_USER@$SSH_HOST -p $SSH_PORT \"cd $TARGET_DIR ; echo \$DOCKER_HUB_PASSWORD | docker login --username tuanloc --password-stdin\""
                    }
                    sh "./service-deploy.sh $images_name $app_name $app_namespace $replica $SSH_USER $SSH_HOST $SSH_PORT $TARGET_DIR"
                    sh "ssh $SSH_USER@$SSH_HOST -p $SSH_PORT \"cd $TARGET_DIR ; docker logout\""
                }
            }
        }
    }
	post {
		always {
			cleanWs()
		}
	}
}
