image:
  name: tuanloc
  tag: service
port: 8080
target_port: 8080
database_username: postgres
database_password: cG9zdGdyZXM=
database_host: 172.22.255.200
database_port: 5432
database_name: room-mate-finance
jwt_secret_key: UThPeklIUm80YnVESUdmaHU0MXBJR0Z1YUNCc3c2QWd4SkhodXJsd0lIUnlZV2tnYm1qaHVxVjBJRlpwNGJ1SGRDQk9ZVzA=
jwt_expire_time: 1440
